### ISSUE TITLE
Issue installing vcf2gwas in Docker

### ISSUE THREAD

**Issue by hangphan** [frankvogt/vcf2gwas#11]
Hi, thanks for creating the nice package. 
I tried installing this in a docker image but got the following error. Could you please help trouble-shooting? Is it possible to set the requirements so that they're not fixed to a version but any version after that, e.g. Python version >=3.9? Thanks
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/7782225/162212107-e9a0a0b9-2a04-4c3d-8a3e-cab94543f506.png">

**Comment by frankvogt** [comment]
Hi,
I am sorry for the delay. I created a docker image so now *vcf2gwas* can be easily run in docker. Just pull the image with `docker pull fvogt257/vcf2gwas` and run *vcf2gwas* normally by replacing in every command `vcf2gwas` with `docker run -v /path/to/current-working-directory/:/vcf2gwas/ fvogt257/vcf2gwas`.
