### ISSUE TITLE
ChildProcessError

### ISSUE THREAD

**Issue by orangelc1221** [frankvogt/vcf2gwas#14]
Hello! I have been tring to run this pipeline but keep receiving this error:

Starting with health_status analysis..
Output will be saved in XXX/Output/Linear Mixed Model/health_status/health_status_20220725_171352/
Reading relatedness matrix..
Calculating linear mixed model..
Traceback (most recent call last):
  File "xxx/vcf2gwas/lib/python3.9/site-packages/vcf2gwas/analysis.py", line 395, in <module>
    Post_analysis.check_return_codes(pc_prefix)
  File "xxx/vcf2gwas/lib/python3.9/site-packages/vcf2gwas/utils.py", line 1562, in check_return_codes
    raise ChildProcessError()
ChildProcessError

vcf2gwas v0.8.7

Initialising..

Any suggestions? Thank you!

Best,
lc

**Comment by frankvogt** [comment]
Hi Ic,
It looks like you're dataset somehow causes GEMMA to abort. What is the command you are using to start the analysis?

**Comment by orangelc1221** [comment]
Hi frankvogt,
I tried the same command with the example: vcf2gwas -v all.vcf.gz -pf pool.csv -ap -lmm
I have binary values (0,1) for the phenotypes.

**Comment by frankvogt** [comment]
Did you try with a different dataset? The test files of vcf2gwas for example? If those work there may be some internal problem with your dataset (wrong formatting within the .vcf etc.).

**Comment by orangelc1221** [comment]
Hi frankvogt,
Yes, the example dataset did work. I also tried different models to run my dataset, seems lmm somehow always aborted in my case, but lm and bayesian models could work. I will try to understand it better. Thank you!
