### ISSUE TITLE
Multivariate Analysis

### ISSUE THREAD

**Issue by M-Ingold** [frankvogt/vcf2gwas#17]
Hello,

This tool is very convenient for running multiple univariate analyses! However, when I tried to run a multivariate analysis, the program only uses the first of my four phenotypes with the following input, running in univariate mode:
vcf2gwas -v input.vcf -lmm --multi -pf phenotypes.csv -k kinship.txt -ap -T 36

I tried using the -m instead of the --multi flag, and also -p 1 -p2 -p3 -p4 instead of -ap.

Could this be a problem with my input or with vcf2gwas?

Thank you,
Markus

**Comment by frankvogt** [comment]
Hi Markus,
There is indeed a bug in vcf2gwas, thanks for pointing it out! It will be fixed in the next update.
Cheers,
Frank
