### ISSUE TITLE
vcf2gwas failing again and again

### ISSUE THREAD

**Issue by vinod1981** [frankvogt/vcf2gwas#2]
Hi, 
I recently started exploring vcf2gwas but it is giving an error for which I couldn't find a solution. 
Command:
vcf2gwas -v js.vcf.gz -pf Pheno_GWAS_Cd_test1.csv -ap -cf pca_gwas1.csv -ac -lmm -M 8000 -T 6

Error log: just from the end
Filtering and converting files

Converting to PLINK BED..
Error: File read failure.
Successfully converted to PLINK BED (Duration: 2 minutes, 16.8 seconds)

Adding phenotypes/covariates to .fam file

Editing .fam file..
All phenotypes chosen
Phenotype(s) added to .fam file
Traceback (most recent call last):
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/analysis.py", line 238, in <module>
    covar_file_name = Processing.make_covarfile(fam, pheno_subset2, subset2, Y)
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/utils.py", line 599, in make_covarfile
    for i in Y:
TypeError: 'NoneType' object is not iterable
Successfully converted to PLINK BED (Duration: 2 minutes, 23.5 seconds)

Adding phenotypes/covariates to .fam file

Editing .fam file..
All phenotypes chosen
Phenotype(s) added to .fam file
Traceback (most recent call last):
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/analysis.py", line 238, in <module>
    covar_file_name = Processing.make_covarfile(fam, pheno_subset2, subset2, Y)
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/utils.py", line 599, in make_covarfile
    for i in Y:
TypeError: 'NoneType' object is not iterable
Analysis successfully completed

Summarizing top SNPs..
Traceback (most recent call last):
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/starter.py", line 428, in <module>
    filenames = Post_analysis.summarizer(path3, path2, pc_prefix3, snp_prefix, n_top, Log, prefix_list)
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/utils.py", line 1002, in summarizer
    for file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/vol/cluster-data/vkumar/miniconda3/bin/output/lmm/summary/top_SNPs'

The problem is that there is a folder generated with name "lm" but I used "lmm" in the command and now it is searching for lmm folder in the path.

**Then I changed the one sub-directory manually to lmm from lm and error shortened like this:**

Preparing files

Checking and adjusting files..
Checking individuals in VCF file..
Checking individuals in phenotype file..
Not all individuals in phenotpye and genotype file match
Removed 0 out of 810 individuals, 810 remaining
Checking individuals in covariate file..
All covariate and genotype individuals match
Removed 0 out of 822 individuals, 822 remaining
In total, removed 12 out of 822 individuals, 810 remaining
Files successfully adjusted

Filtering and converting files

Converting to PLINK BED..
Successfully converted to PLINK BED (Duration: 35.6 seconds)

Adding phenotypes/covariates to .fam file

Editing .fam file..
Phenotype(s) added to .fam file
Traceback (most recent call last):
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/analysis.py", line 238, in <module>
    covar_file_name = Processing.make_covarfile(fam, pheno_subset2, subset2, Y)
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/utils.py", line 599, in make_covarfile
    for i in Y:
TypeError: 'NoneType' object is not iterable
Analysis successfully completed

Summarizing top SNPs..
Couldn't find files to summarize!
Clean up successful 

vcf2gwas has been successfully completed! 
Runtime: 7 minutes, 43.9 seconds
 
This error is still there.
What to do?

Thanks,

Vinod

**Comment by frankvogt** [comment]
Hi Vinod,

Thank you for your email!
Would you mind sending me your input files so that I can replicate the
error?

Thanks,

Frank

Am Do., 24. Juni 2021 um 22:47 Uhr schrieb vinod1981 <
***@***.***>:

**Comment by vinod1981** [comment]
Hi Frank,
Thanks for reaching out.
But the vcf file is very big around 6G compressed. How to do that?
Thanks,

Vinod,

**Comment by frankvogt** [comment]
Hi Vinod,

Maybe you can share it via google drive or something similar?
Alternatively you can send me just the phenotype + covariate + log files.

Best,

Frank

Am Fr., 25. Juni 2021 um 16:27 Uhr schrieb vinod1981 <
***@***.***>:

**Comment by vinod1981** [comment]
Hi Frank,
Should I share them here or on a specific email?
Thanks,
VInod,

**Comment by vinod1981** [comment]
Find the attached files.

Vinod,


Sent from Mail for Windows 10

**Comment by frankvogt** [comment]
You can share the files with my email: frvogt@gmail.com

**Comment by frankvogt** [comment]
Bug was fixed where internally not all covariates were passed on when a certain combination of options was selected

**Comment by vinod1981** [comment]
Hi Frank,
Is it a reply for my other request or you are adding something to this issue?
Because in other issue, I am requesting if it is possible to just see the significant threshold line and not label the SNPs in Manhattan plot.
Thanks,
Vinod,

**Comment by frankvogt** [comment]
No this was just to clarify what the issue was and that it has been fixed
