### ISSUE TITLE
threshold line in the Manhattan plot

### ISSUE THREAD

**Issue by vinod1981** [frankvogt/vcf2gwas#3]
Hi,
Is it possible to just have a significance threshold line in the Manhattan plot but not to label them? Because it is annoying when I have a lot of significant SNPs and the program takes endless time in finishing the labeling. But I am interested to put a threshold line in the Manhatttan plot which is important to see the SNPs passing the threshold.
Thanks,
Vinod,

**Comment by frankvogt** [comment]
I added the option -nl / --nolabel to remove the labels of the significant SNPs in the manhattan plot

**Comment by vinod1981** [comment]
Thank you very much Frank for this update. 
I appreciate it.

Vinod,
