### ISSUE TITLE
Singularity?

### ISSUE THREAD

**Issue by Jolleboll** [frankvogt/vcf2gwas#30]
Hello!

I was hoping to get this running without root, since Docker is not available on compute clusters. I see there's an older issue about this but it was closed by the submitter before you had a chance to reply.

The sif image created by singularity from your Docker image does not seem to have any executable "vcf2gwas" anywhere in its file tree. There is no fvogt257 folder anywhere, either.

I'm fairly new to containers so don't immediately see how to hack this until it works. Do you have any advice, Frank?

Big thanks in advance!

Joel

**Comment by nboelte** [comment]
We got a request from one of our HPC users that wanted to install vcf2gwas. We ended up giving them this apptainer recipe, which might also be useful for you.

```
Bootstrap: docker
From: fvogt257/vcf2gwas

%environment
    source activate python-app

%runscript
    exec vcf2gwas "$@"
```

**Comment by Jolleboll** [comment]
Hello and thank you for that! I went with PLINK instead, so don't need this at the moment. But I very much appreciate that you thought of me! :)


Joel
