### ISSUE TITLE
`Too many phenotype input files for available ressources` [sic]

### ISSUE THREAD

**Issue by hhg7** [frankvogt/vcf2gwas#4]
I'm running a test of my recent installation:

```
(myenv) con@V:~/Downloads/tmp$ vcf2gwas -v test

vcf2gwas v0.6.1 

Initialising..

Copying example input files to current working directory..
Copying README and LICENSE files..
Start time: Mon, 19 Jul 2021 14:53:50

Parsing arguments..
Genotype file: example.vcf.gz
Phenotype file(s): example.csv
Arguments parsed successfully

Preparing files
Error: Too many phenotype input files for available ressources
```

this is being done in an empty directory, I don't know where there can be *any* input files.

**Comment by frankvogt** [comment]
This is caused by the vcf2gwas using the internal test files and it seems that there is not enough memory available to analyze the test phenotype (1 GB is the minimal requirement). Try to set the memory manually to at least 1000 (MB) with the -M / --memory option.
To check the resources available to vcf2gwas you can type "vcf2gwas -h" and check the values displayed at the "-M" and "-T" options

**Comment by frankvogt** [comment]
Also, please update to the newest version by running "conda update vcf2gwas -c conda-forge -c bioconda -c fvogt257"

**Comment by hhg7** [comment]
Hi Frank,

thanks.  I've re-installed and updated conda as you said, but am now running into new errors:
```

(vcf2gwas) con@V:~/Downloads$ vcf2gwas -v test -T 9

vcf2gwas v0.6.2 

Initialising..

Copying example input files to current working directory..
Copying README and LICENSE files..
Start time: Wed, 21 Jul 2021 09:32:08

Parsing arguments..
Genotype file: example.vcf.gz
Phenotype file(s): example.csv
Arguments parsed successfully

Preparing files

Error: No logical cores available!
```
setting the # of cores with `-T` doesn't seem to work :(

**Comment by frankvogt** [comment]
Can you check with "vcf2gwas -h" under the -T option which number of cores is displayed in brackets?

**Comment by frankvogt** [comment]
Can the issue be closed?

**Comment by hhg7** [comment]
Yes please close the issue
