### ISSUE TITLE
NameError: name 'geno_pca_switch' is not defined

### ISSUE THREAD

**Issue by vinod1981** [frankvogt/vcf2gwas#7]
Hi,
I am  having this error after updating vcf2gwas. 

```
Traceback (most recent call last):
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/starter.py", line 139, in <module>
    if geno_pca_switch == True:
NameError: name 'geno_pca_switch' is not defined

```
vcf2gwas is working fine without pca but once the covariates are added it is giving this error. I have checked the name and they are completely fine and matching with each other in all the file.

And also the -sv option is not responding to the value given in the script. Please have a look into it.

Thanks,

Vinod,

**Comment by frankvogt** [comment]
Hi Vinod,
There was a faulty update on my side, sorry for that.
The issues should be fixed now!
