### ISSUE TITLE
vcf2gwas error after updating to new version

### ISSUE THREAD

**Issue by vinod1981** [frankvogt/vcf2gwas#9]
Hi Frank,
When I am running vcf2gwas, I am getting error:

Command line: 
`/vol/cluster-data/vkumar/miniconda3/envs/myenv/bin/vcf2gwas -v /prj/pflaphy-robot/genotypeGVCF_allsamples_updated/linkimpute/output_all_imputed_final_chr7Mod_js_GT_EA_js.vcf.gz -pf /prj/pflaphy-robot/genotypeGVCF_allsamples_updated/linkimpute/vcf2gwas/soil_pH/EA/soil_pH_EA_updated.csv -ap -cf /prj/pflaphy-robot/genotypeGVCF_allsamples_updated/linkimpute/vcf2gwas/soil_pH/EA/pca_EA_updated_cofactor_chr8.csv -ac -lmm -sv 5 -nl -q 0.01 -o /prj/pflaphy-robot/genotypeGVCF_allsamples_updated/linkimpute/vcf2gwas/soil_pH/pca_with_cof/`

Parsing arguments..
Genotype file: output_all_imputed_final_chr7Mod_js_GT_EA_js.vcf.gz
Phenotype file(s): soil_pH_EA_updated.csv
Covariate file: pca_EA_updated_cofactor_chr8.csv
Arguments parsed successfully

Preparing files

Traceback (most recent call last):
  File "/vol/cluster-data/vkumar/miniconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/starter.py", line 348, in <module>
    if set(Y).issubset([i+1 for i in list(range(l_covar))]) == False:
TypeError: 'NoneType' object is not iterable

What could be the reason for this?

Thanks,

**Comment by frankvogt** [comment]
Hi Vinod,
What is the command you used to run the analysis?
